### ISSUE TITLE
Allow for specific replacement for NaN/NaT values

### ISSUE THREAD

**Issue by rompom** [smarie/python-azureml-client#11]
In the case when we have an empty dataframe, the payload is converted to a list of NaT or Nan values.
We would like to have a possible conversion to null, "", or something we define ourselves.

**Example :
Input csv**

Timestamp,Class,Code,Parameter
,,,

**Resulting dataframe :**
Timestamp,Class,Code,Parameter
NaT,nan,nan,nan

**Resulting payload :**
"EventRecords": {"ColumnNames": ["Timestamp", "Class", "Code", "Parameter"], "Values": [["NaT", NaN, NaN, NaN]]}

**Comment by smarie** [comment]
Thanks @rompom ! Can you please provide some minimal code to reproduce the issue so that I better see what you're referring to ?

**Comment by rompom** [comment]
Basically, when I do this :
outputs = azmlclient.execute_rr(self.api_key, self.url, inputs=self.parsed_inputs, params=self.params)

I would like a way to set how the Nan/Nat will be handled when later in the library in service_calls.py we have the : 
# 1- Create the query body
    request_body = rr_client.create_request_body(inputs, params)

**Comment by smarie** [comment]
I created a PR that should fix it. Can you confirm that it fixes the issue in your case ?

**Comment by smarie** [comment]
#12

**Comment by smarie** [comment]
I'll merge the PR now, as I'm about to release a new version. If this does not match your expactations feel free to open a new issue :)
